str_ = input(str('Enter new string:'))
print(f'1) {str_[2]}')
print(f'2) {str_[1:]}')
print(f'3) {str_[:5]}')
print(f'4) {str_[:-2]}')
print(f'5) {str_[1::2]}')
print(f'6) {str_[::2]}')
print(f'7) {str_[::-1]}')
print(f'8) {str_[::-2]}')
print(f'9) {len(str_)}')